### ISSUE TITLE
Use latest minor Leanplum version?

### ISSUE THREAD

**Issue by benmarten** [mparticle-integrations/mparticle-android-integration-leanplum#4]
Looks like Android SDK 3.0.1 is hardcoded here: https://github.com/mparticle-integrations/mparticle-android-integration-leanplum/blob/master/build.gradle#L23

Does it make sense to use 3.* or at least 3.0.* to get latest bug fixes from our end?
Happy to send a Pr ;)

**Comment by samdozor** [comment]
Hi @benmarten sorry for the delay in responding here. We'll always be quick to respond in the primary github repo of the SDK.

Unfortunately we can't use wildcards as that will cause non-deterministic builds for customers. Customers can however always override our hard-coded dependency if they wish.
